name: Sync AMA Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours at minute 0

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Sync and commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        ./sync.py --force --parallel data/20*AMA.json
            
        git add data/*-AMA.json || echo no .json changes
        git add data/*.synced.jsonl || echo no .synced.jsonl changes
        git add data/*.timestamps.json || echo no .timestamps.json changes

        ./render.py data/20*AMA.json
        
        git add docs/index.html || echo no docs/index.html changes
        
        if ! git diff --cached --quiet; then
            git commit -m "Sync AMA data"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            
            # Trigger the static deployment workflow
            gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
            gh workflow run static.yml
        else
            echo "No changes to commit"
        fi
