name: Sync AMA Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours at minute 0

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Sync and commit each file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        for file in data/20*AMA.json; do
            echo "Processing $file"
            ./sync.sh --force "$file"
            
            # Add and commit changes for this specific file
            base_name=$(basename "$file" .json)
            git add "data/${base_name}.synced.jsonl"
            git add "data/${base_name}.timestamps.json"
            
            if ! git diff --cached --quiet; then
                git commit -m "Sync AMA data for ${base_name} [skip ci]"
                git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            else
                echo "No changes for ${base_name}"
            fi
        done

        # Final sync and index update
        echo "Running final sync on all files"
        ./sync.sh data/20*AMA.json
        
        if git diff --quiet data/index.html; then
            echo "No changes to index.html"
        else
            git add docs/index.html
            git commit -m "Update AMA index"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        fi
        
