name: Sync AMA Data

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run sync script
      run: |
        chmod +x sync.sh
        ./sync.sh data/20*AMA.json

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/*.synced.jsonl
        git add data/*.timestamps.json
        if ! git diff --quiet || ! git diff --cached --quiet; then
            git commit -m "Sync AMA data"
            git push
        else
            echo "No changes to commit"
        fi

        
        
